name: Create the main structure for the project, once.

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout own structure
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Create the folder structure
      run: |
        mkdir automated-scripts
        touch automated-scripts/process-fortinet-compatible-list.py
        mkdir -p repositories/blocklistproject/List
        mkdir -p repositories/StevenBlack/hosts
        touch repositories/blocklistproject/List/.gitkeep
        touch repositories/StevenBlack/hosts/.gitkeep

    - name: Clone awesome repositories
      uses: actions/checkout@v2

    - name: Cloning repository fortinet-compatible-lists...
      run: git clone https://github.com/openthreatfeeds/fortinet-compatible-lists.git projects/fortinet-compatible-lists

    - name: Cloning repository blocklistproject/Lists...
      run: git clone https://github.com/blocklistproject/Lists.git repositories/blocklistproject/List

    - name: Cloning repository StevenBlack/hosts...
      run: git clone https://github.com/StevenBlack/hosts.git repositories/StevenBlack/hosts

    - name: Create the new structure for the main-project
      run: |
        mkdir -p projects/fortinet-compatible-lists/lists/blocklistproject/Lists/
        mkdir -p projects/fortinet-compatible-lists/lists/StevenBlack/hosts/
        touch projects/fortinet-compatible-lists/.gitkeep
        touch projects/fortinet-compatible-lists/lists/blocklistproject/Lists/.gitkeep
        touch projects/fortinet-compatible-lists/lists/StevenBlack/hosts/.gitkeep

    - name: Commit and push changes to the main-project
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Automated project initialization with GitHub actions"
        git push origin main

    - name: Commit and push to the side-project
      uses: actions/checkout@v2
      with:
        repository: 'https://github.com/openthreatfeeds/fortinet-compatible-lists.git'
        token: ${{ secrets.MAIN_PROJECT }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Automated project initialization with GitHub actions"
          git push origin main
        working-directory: projects/fortinet-compatible-lists
