name: Create the main structure for the project, once.

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout own structure
      uses: actions/checkout@v2

    - name: Create the folder structure
      run: |
        mkdir automated-scripts
        touch automated-scripts/process-fortinet-compatible-list.py
        mkdir -p repositories/blocklistproject/List
        mkdir -p repositories/StevenBlack/hosts
        touch repositories/blocklistproject/List/.gitkeep
        touch repositories/StevenBlack/hosts/.gitkeep
        echo 'projects/' >> .gitignore

    - name: Cloning repository fortinet-compatible-lists...
      uses: actions/clone@last
      with:
        repository: https://github.com/openthreatfeeds/fortinet-compatible-lists.git
        path: projects/fortinet-compatible-lists
        depth: 1

    - name: Cloning repository blocklistproject/Lists...
      uses: actions/clone@last
      with:
        repository: https://github.com/blocklistproject/Lists.git
        path: repositories/blocklistproject/List
        depth: 1

    - name: Cloning repository StevenBlack/hosts...
      uses: actions/clone@last
      with:
        repository: https://github.com/StevenBlack/hosts.git
        path: repositories/StevenBlack/hosts
        depth: 1

    - name: Create the new structure for the main-project
      run: |
        mkdir -p projects/fortinet-compatible-lists/lists/blocklistproject/Lists/
        mkdir -p projects/fortinet-compatible-lists/lists/StevenBlack/hosts/
        touch projects/fortinet-compatible-lists/.gitkeep
        touch projects/fortinet-compatible-lists/lists/blocklistproject/Lists/.gitkeep
        touch projects/fortinet-compatible-lists/lists/StevenBlack/hosts/.gitkeep

    - name: Commit and push changes to the main-project

    - name: Configure git
      uses: actions/setup-git@latest
      with:
        email: action@github.com
        username: "GitHub Action"
        working-directory: projects/fortinet-compatible-lists

    - name: Add
      uses: git/add@latest
      with:
        path: ./projects/fortinet-compatible-lists

    - name: Commit
      uses: git/commit@latest
      with:
        message: "Automated project initialization with GitHub actions"
        working-directory: projects/fortinet-compatible-lists

    - name: Push
      uses: git/push@latest
      with:
        repository: https://github.com/openthreatfeeds/fortinet-compatible-lists
        branch: main
        ref: HEAD
        working-directory: projects/fortinet-compatible-lists
        
