name: Create the main structure for the project, once.

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main-project
        uses: actions/checkout@v4

      - name: Create the folder structure for the main-project
        run: |
          mkdir automated-scripts
          echo '# empty file' >> automated-scripts/process-fortinet-compatible-list.py
          mkdir -p repositories/blocklistproject/List
          mkdir -p repositories/StevenBlack/hosts
          touch repositories/blocklistproject/List/.gitkeep
          touch repositories/StevenBlack/hosts/.gitkeep
          mkdir -p projects/fortinet-compatible-lists
          touch projects/fortinet-compatible-lists/.gitkeep
          echo 'projects' >> .gitignore

      - name: Cloning repository "openthreatfeeds/fortinet-compatible-lists"...
        run: git clone https://github.com/openthreatfeeds/fortinet-compatible-lists.git projects/fortinet-compatible-lists

      - name: Create the folder structure for the side-project
        working-directory: projects/fortinet-compatible-lists
        run: |
          mkdir -p lists/blocklistproject/Lists/
          mkdir -p lists/StevenBlack/hosts/
          touch lists/blocklistproject/Lists/.gitkeep
          touch lists/StevenBlack/hosts/.gitkeep

      - name: Cloning repository "blocklistproject/Lists"...
        run: git clone https://github.com/blocklistproject/Lists.git repositories/blocklistproject/List

      - name: Cloning repository "StevenBlack/hosts"...
        run: git clone https://github.com/StevenBlack/hosts.git repositories/StevenBlack/host

      - name: Commit and push the side-project
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Automated project initialization with GitHub actions"
          git push origin main
        
      - name: Commit and push the side-project
        working-directory: projects/fortinet-compatible-lists
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Automated project initialization with GitHub actions"
          git push origin main
